---
- hosts: all
- name: create ec2 instances
  hosts: 127.0.1.1
  becomes: yes
  become_method: sudo
  gather_facts: true
  roles: 
    - ec2
    
    s:
    keypair: chitta_devops
    instance_type: t2.micro
    security_group: chitta_dev
    image:  ami-0c1a7f89451184c8b (64-bit x86)
    region: us-south-1
~                         
