---
- name: ec2 installance
  hosts: localhost
  tasks:
  - name: launch ec2 instance
    ec2: 
      instance_type: t2.micro
      image:  ami-0c1a7f89451184c8b (64-bit x86)
      security_group: chitta_dev
      region: us-south-1
      wait: yes
      group: ansible
      count: 1
      vpc_subnet_id: default
      assign_public_ip: yes
      aws_access_key: AKIAWYWDFTIITPYKAP4O
      aws_access_key: XA6uHVbXV8ttKXZSCCrn63tLhmswnIEHnTZP1dQm
      
